### ISSUE TITLE
Dependency on NLog

### ISSUE THREAD

**Issue by hellfirehd** [Timmoth/AptacodeTaskPlex#1]
Instead of the explicit dependency on NLog, consider using an abstraction so that consumers of the library can have a choice in their logging provider.

Now that MS has logging [baked in](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/), [ILogger](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger) is a reasonable choice. Alternatively you could consider something like [LibLog](https://github.com/damianh/LibLog).

**Comment by hellfirehd** [comment]
BTW: Found you [here](https://www.reddit.com/r/csharp/comments/djcra8/ive_never_had_anyone_look_at_my_code_can_anyone/) and thought I'd drop by.

**Comment by Timmoth** [comment]
Brilliant Idea! I'm about to rewrite all of my GitHub projects to use a DI container, which will give me even more reason to abstract away from NLog.

Do you have any recommendations for IoC frameworks?

**Comment by hellfirehd** [comment]
I think you might be misunderstanding IoC... Usually the Application consuming the library is what implements and relies on IoC/DI.  Libraries/Packages are specifically designed and written to play nice with IoC without necessarily having a dependency on a particular IoC vendor.  If you want a great example of this, check out [Rebus](https://github.com/rebus-org/Rebus).  The main Rebus library has a very simple abstraction for service location and then makes [available](https://github.com/rebus-org/Rebus.LightInject) [several](https://github.com/rebus-org/Rebus.Ninject) [different](https://github.com/rebus-org/Rebus.StructureMap) [packages](https://github.com/rebus-org/Rebus.SimpleInjector) [supporting](https://github.com/rebus-org/Rebus.DryIoc) [various](https://github.com/rebus-org/Rebus.CastleWindsor) [different](https://github.com/rebus-org/Rebus.ServiceProvider) [containers](https://github.com/rebus-org/Rebus.Autofac).  (In many cases, the packages were contributed by the IoC container authors.)

If a library is complex enough to need an internal container, then like logging, [Microsoft.Extensions.DependencyInjection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection) is probably your best choice as every single other IoC container has offered adapters to make their containers work with [IServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider).

But since you asked, my favorite containers are [Lamar](https://github.com/jasperfx/lamar) and [LightInject](https://github.com/seesharper/LightInject).

**Comment by Timmoth** [comment]
Thanks man, I've removed the dependancy on Ninject
Cheers for the suggestion, If you have any others I'd love to hear your thoughts!!

**Comment by hellfirehd** [comment]
No problem. Feel free to ask me anything. I don’t know everything but I have been doing this for a long time.
